volumes:
  db_data:
    name: predocs-db_data
    labels:
      com.description: "This volume is used for MySQL"
  storage:
    name: predocs-storage
    labels:
      com.description: "This volume is used for data storage"
  redis_data:
    name: predocs-redis_data
    labels:
      com.description: "This volume is used for Redis"

networks:
  rede_predocs:
    name: rede_predocs

services:

  predocs:
    build:
      context: ./
      dockerfile: docker/Dockerfile.predocs
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/
    networks:
      - rede_predocs
    depends_on:
      - app
      - api
      - db
      - redis

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.app
    env_file:
      - .env
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    ports:
      - "8000:80"
    networks:
      - rede_predocs
    depends_on:
      - api

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    env_file:
      - .env
    volumes:
      - ./api/:/var/www/html
      - storage:/storage
    networks:
      - rede_predocs
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./
      dockerfile: docker/Dockerfile.db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33306:3306"
    networks:
      - rede_predocs

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - rede_predocs
