version: '3'
volumes:
  db_data:
networks:
  rede_predocs:
services:
  predocs:
    build:
      context: ./
      dockerfile: Docker/Dockerfile.predocs
    volumes:
      - ./:/var/www/html
    ports:
      - "7000:80"
    networks:
      - rede_predocs

  frontend:
    build:
      context: ./
      dockerfile: Docker/Dockerfile.frontend
    volumes:
      - ./app/:/usr/local/apache2/htdocs
    ports:
      - "8000:80"
    networks:
      - rede_predocs

  server:
    build:
      context: ./
      dockerfile: Docker/Dockerfile.server
    volumes:
      - ./server/:/var/www/html
    ports:
      - "9000:80"
    networks:
      - rede_predocs

  bd:
    build:
      context: ./
      dockerfile: Docker/Dockerfile.bd
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rede_predocs
