version: '3'

volumes:
  db_data:
    name: db_data
    labels:
      com.example.description: "This volume is used for MySQL"
  storage:
    name: storage
    labels:
      com.example.description: "This volume is used for data storage"

networks:
  rede_predocs:

services:

  predocs:
    build:
      context: ./
      dockerfile: docker/Dockerfile.predocs
    volumes:
      - ./:/var/www/html/
    env_file:
      - .env
    networks:
      - rede_predocs
    depends_on:
      - bd
      - app
      - api

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - rede_predocs

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    volumes:
      - ./api/:/var/www/html
      - storage:/storage
    env_file:
      - .env
    networks:
      - rede_predocs

  bd:
    build:
      context: ./
      dockerfile: docker/Dockerfile.bd
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - rede_predocs
