version: '3'
volumes:
  db_data:
networks:
  rede_predocs:
services:

  predocs:
    build:
      context: ./
      dockerfile: docker/Dockerfile.predocs
    volumes:
      - ./:/var/www/html
    ports:
      - "7000:80"
    networks:
      - rede_predocs

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.app
    volumes:
      - ./app/:/usr/local/apache2/htdocs
    ports:
      - "8000:80"
    networks:
      - rede_predocs

  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile.api
    volumes:
      - ./api/:/var/www/html
    ports:
      - "9000:80"
    networks:
      - rede_predocs

  bd:
    build:
      context: ./
      dockerfile: docker/Dockerfile.bd
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rede_predocs
