# Dockerfile.predocs
FROM php:8.3-apache

RUN a2enconf charset
RUN a2enmod rewrite
RUN a2enmod headers
RUN docker-php-ext-install pdo_mysql

# Set UTF-8 encoding for HTTP requests
RUN echo "AddDefaultCharset UTF-8" >> /etc/apache2/conf-available/charset.conf

# Reinicia o apache
RUN service apache2 restart
