# Dockerfile.api
FROM php:8.3-apache

COPY ./api /var/www/html

# instalando os módulos necessários
RUN a2enmod rewrite
RUN a2enmod headers
RUN docker-php-ext-install pdo_mysql
RUN service apache2 restart
