# Dockerfile.server
FROM php:8.3-apache

COPY ./server /var/www/html

# instalando os módulos necessários
RUN a2enmod rewrite
RUN a2enmod headers
RUN service apache2 restart

RUN chmod -R 777 /var/www/html
